// jewelryData.js
const jewelryData = {
  types: [
    "Gems",
    "Beads",
    "Diamonds",
    "Jewelry",
    "Astrology Gems",
    "Pearls",
    "Corals",
  ],
  subtypes: {
    Gems: ["Precious", "Semi-precious"],
    Beads: ["Gemstone", "Glass", "Metal", "Wood", "Plastic", "Ceramic"],
    Diamonds: ["White", "Yellow", "Pink", "Blue", "Green", "Black"],
    Jewelry: [
      "Rings",
      "Necklaces",
      "Bracelets",
      "Earrings",
      "Pendants",
      "Brooches",
      "Anklets",
      "Cufflinks",
      "Body jewelry",
    ],
    "Astrology Gems": [
      "Ruby",
      "Pearl",
      "Coral",
      "Emerald",
      "Yellow Sapphire",
      "Diamond",
      "Blue Sapphire",
      "Hessonite",
      "Cat's Eye",
    ],
    Pearls: ["Akoya", "South Sea", "Tahitian", "Freshwater"],
    Corals: ["Red Coral", "Pink Coral", "Bamboo Coral", "Blue Coral"],
  },
  shapes: {
    Gems: [
      "Round",
      "Brilliant",
      "Oval",
      "Marquise",
      "Pear",
      "Cabochon",
      "Square",
      "Emerald cut",
      "Asscher",
      "Baguette",
    ],
    Beads: [
      "Round",
      "Cylindrical",
      "Square",
      "Faceted",
      "Bicone",
      "Tricone",
      "Heishi",
      "Barrel",
      "Oval",
      "Donut",
    ],
    Diamonds: [
      "Round",
      "Brilliant",
      "Oval",
      "Marquise",
      "Pear",
      "Cabochon",
      "Square",
      "Emerald cut",
      "Asscher",
      "Baguette",
    ],
    Jewelry: [
      "Styles: Vintage",
      "Modern",
      "Minimalist",
      "Statement",
      "Classic",
      "Trendy",
    ],
    "Astrology Gems": [
      "Often cabochons or beads, based on traditional practices",
    ],
    Pearls: ["Shapes: Round", "Button", "Oval", "Baroque", "Keshi"],
    Corals: ["Shapes: Cabochons", "Beads", "Carvings"],
  },
  prices: [
    "1k - 10k",
    "10k - 20k",
    "20k - 30k",
    "30k - 40k",
    "40k - 50k",
    "50k - 60k",
    "60k - 70k",
    "70k - 80k",
    "80k - 90k",
    "90k - 1L",
  ],
};

export default jewelryData;
